### ISSUE TITLE
Plugin has Crashed

### ISSUE THREAD

**Issue by Mobeeuz** [mpm11011/galaxy-integration-rpcs3#10]
Help for the people getting this issue:

You are expected to download and run GIT so you can update submodules. If, like me, you have no interest in doing this, go to **https://github.com/mpm11011/devita** and download the three files there. Place them into the **rpcs3_80F9D16B-5D72-4B95-9D46-2A1EF417C1FC\devita** folder and you're good.

Just remember to keep this module updated as well when updating the RPCS3 plugin.

**Comment by mpm11011** [comment]
I've updated the readme to include installing with git and without. I hope that clears up any confusion. I'll leave this issue pinned so people can see it.

**Comment by molitar** [comment]
Ok tried copying the 3 files and NOPE did not work.. Still plugin has crashed. I used the GIT method to install it.

**Comment by mpm11011** [comment]
Please submit a new issue and follow the template. Thanks!
