### ISSUE TITLE
Games Not Importing

### ISSUE THREAD

**Issue by Curotos** [mpm11011/galaxy-integration-rpcs3#11]
when I installed the plugin I got it to connect on Gog, but none of the games showed up. I'm thinking it was because I didn't specify where my games folder was because I couldn't find where to edit that. Any help would be much appreciated!

**Comment by Mobeeuz** [comment]
Main page, under [Configuration](https://github.com/mpm11011/galaxy-integration-rpcs3#configuration).

**Comment by mpm11011** [comment]
What I had not realized is that RPCS3 allows you to put your games anywhere, and it stores the game entries in `games.yml`. So I need to add that feature to this plugin.

**Comment by mpm11011** [comment]
As of version 0.5, importing games should be much simpler. We now rely on the `games.yml` file, which RPCS3 maintains, to show us where your disc games are, while `/dev_hdd0/games` is where your PSN games are.

Let me know if your issue has been resolved. Keep in mind that even when working properly, the plugin may take a while to do a first-time import.

**Comment by Eremeir** [comment]
Before 0.5, I wasn't able to import games, since 0.5, my plugin crashes on startup.
Devita submod was installed and I did everything in the installation section. Can't figure it out.

**Comment by Curotos** [comment]
Once I put my games in the hddev0001 folder they all imported, let me just say thank you for making this possible!

**Comment by mpm11011** [comment]
@Eremeir could you upload the log file? On Windows, you can find it at `C:\ProgramData\GOG.com\Galaxy\logs\plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log`.

**Comment by Eremeir** [comment]
[plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3640326/plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log)

**Comment by mpm11011** [comment]
It's filled with what looks like a network timeout error. If you have a log.0 or log.1 file, upload those as well.

**Comment by Eremeir** [comment]
There are 10 logs and they all are filled with the same spew.

**Comment by mpm11011** [comment]
That sounds like it's gonna need it's own issue. Please start a new thread.

I'm not sure it's even related to the plugin itself, because the error points directly to the Galaxy API. We'll see - I need some time to research it.
