### ISSUE TITLE
Naruto Storm Generations Not Showing Up?

### ISSUE THREAD

**Issue by Curotos** [mpm11011/galaxy-integration-rpcs3#13]
When I got my games to import into galaxy they all showed up but Naruto didn't have any of the metadata for it, so I added images to it myself and it was running fine from that. Today, when I logged on it, was no longer in galaxy but it still works through just rpcs3. I was wondering if there was any fix for this?

**Comment by mpm11011** [comment]
See [this comment](https://github.com/mpm11011/galaxy-integration-rpcs3/issues/8#issuecomment-532948935). If you plug the game ID for it into that URL, and you see the results come back with `"type": "spam"` then that's maybe why it disappeared.

**Comment by Curotos** [comment]
Alright, I just peeped it out and it was coming up as spam, is there any way to find the correct ID?

**Comment by mpm11011** [comment]
If it's been marked as spam, I'm told you have to file a report with GOG. You should be able to do so from within Galaxy. Gear icon > Report issue.

**Comment by Curotos** [comment]
Alright, so I just tell them that the naruto game has been marked as spam in their database?

**Comment by mpm11011** [comment]
I've never tried it, but that seems to be the recommended action. If I were them, I would also want to see the URL with your game ID so they can see how it was marked as spam.
