### ISSUE TITLE
The forever load of death [0.61]

### ISSUE THREAD

**Issue by Eremeir** [mpm11011/galaxy-integration-rpcs3#14]
**Describe the bug**
Okay seriously I'm sorry that I keep showing up here.
I've managed to import a game on 0.60, but the update to 0.61 causes the plugin to stay in a constant state of Connecting...

I can't disconnect or connect, it just starts like this, even on a fresh install.
Downgrading to [0.6] causes the behavior to disappear.

**When does the bug occur?**
The behavior happens on both fresh install, and update. Immediately on launch of the client and seemingly forever.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/20992519/65559896-25494c00-df02-11e9-9cd0-5fa859055892.png)

**Your setup**
 - Win10 64 [0.61]
 - RPCS3 Version: 0.0.7-8755-a44b1018 Alpha
 - Game ID's causing trouble: Technically none, but I was unable to import any new games while the plugin is stuck on connecting. Can import the same game on [0.60]. Tested with BCUS98103.
 - Python Version (if applicable): 3.5.4

**Logs**
Upload the following logs and files:
[plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3650023/plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log)

[GalaxyClient.log](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3650024/GalaxyClient.log)

[config.zip](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3650027/config.zip)

Log complains that localusername doesn't exist. It does.
![image](https://user-images.githubusercontent.com/20992519/65560283-9d644180-df03-11e9-82a3-c73bfd9838c5.png)

**Comment by mpm11011** [comment]
Sorry you're constantly the guinea pig lol
Found the problem, it was me missing one more thing related to paths. Updated with 0.62. Try that.

**Comment by Eremeir** [comment]
[0.62] Seems to have fixed it. Working perfectly on my end.
