### ISSUE TITLE
Press connect for PS3 Colecovision Plugin has crashed retry.

### ISSUE THREAD

**Issue by molitar** [mpm11011/galaxy-integration-rpcs3#16]
**Describe the bug**
Installed plugin and when I tried to use the connect button. Plugin has crashed retry.  Only a single game in my rpcs3 right now. Used Windows GIT for install and had no errors.

**When does the bug occur?**
After pressing connect button

**Your setup**
 - OS and Version: Windows 10 Pro build 1903
 - RPCS3 Version: 0.0.7-8779
 - Game ID's causing trouble: Ar nosurge: Ode to an Unborn Star DOWNLOAD [NPUB31579]
 - Python Version (if applicable):

**Logs**
Upload the following logs and files:
 - `plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log`:
 - `GalaxyClient.log`:
 - `config.py`:

[config.py.txt](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3664562/config.py.txt)
[plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3664563/plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log)
[Uploading GalaxyClient.log…]()

**Comment by molitar** [comment]
New log file seems that original had when git first failed install and I had to use the deprecated windows release.. Here is clean log file after I deleted all old log files.

[plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3664579/plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log)

**Comment by mpm11011** [comment]
So, a couple of things from the log:

1. You specify `self.main_directory = 'G:\rpcs3/'` with a mix of backslash and forward slash. My code attempts to clean that up, but clearly Python is interpreting `\r` as a carriage return. Which is why you see this in your first log:

```
2019-09-27 04:27:24,213 - root - ERROR - G:
pcs3\rpcs3.exe not found in RPCS3 directory.
```

2. Your devita folder must not have been retrieved properly, because I see this log line:

```
  File "C:\Users\malaac\AppData\Local\GOG.com\Galaxy\plugins\installed\rpcs3_80F9D16B-5D72-4B95-9D46-2A1EF417C1FC\devita\sfo.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

`sfo.py` is not an HTML file... so would you mind uploading that file? I'm curious to see what went wrong, and the likely fix will be to delete the contents of that folder and trying to get that submodule again.

**Comment by molitar** [comment]
Ok here is the file that was retrieved.

[sfo.py.txt](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3664666/sfo.py.txt)

Ok I used the manual method instead of git and it worked but now I find that for some reason my games.yml file is blank so no games display for it.   Any idea why that would be?  The single game I have works great do you think they removed the need for that file in latest rpcs3 version?

**Comment by mpm11011** [comment]
Yeah that's definitely not the python script it should be - that looks like the whole GitHub webpage it was on.

So, the "N" in "NPUB31579" means this is a PSN game, not a Blu-ray game ("B"). I don't know the reason, but PSN games are not stored in games.yml. They should live in `dev_hdd0\game`, and the plugin knows to read from that location.

If the plugin connects correctly now, give Galaxy a couple of minutes to do the import. Monitor [this page](https://gamesdb.gog.com/platforms/vision/external_releases/NPUB31579) and report back if you see `"type" : "spam"` show up.

**Comment by molitar** [comment]
ok game not showing that I have at all.  

error | "not_found"
-- | --
error_description | "Release with per platform id: vision_NPUB31579 not found"

this is what I get.

**Comment by mpm11011** [comment]
Upload your latest log, the one that now connects properly. 

In what folder do you keep the game?

**Comment by molitar** [comment]
The default folder is at G:\rpcs3.

the game installed to G:\rpcs3\dev_hdd0\game\NPUB31579


[plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC .txt](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3664989/plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.txt)

**Comment by massimilianodelliubaldini** [comment]
Alright, turns out there was a bug with empty YML files. I fixed it in Version 0.63. Try that, let me know if it works.

**Comment by molitar** [comment]
Ok it now shows but it reports unable to download data.  

![Screenshot_1](https://user-images.githubusercontent.com/16074561/65810685-4668a180-e17b-11e9-93fe-3899d7cb6601.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/16074561/65810686-4d8faf80-e17b-11e9-989e-751691823be2.jpg)

**Comment by massimilianodelliubaldini** [comment]
Galaxy pulls game data from IGDB. [Here's](https://m.igdb.com/games/ar-nosurge-ode-to-an-unborn-star) the page for that game. There's no cover art, among other things missing. Other users on Reddit and GitHub reported adding stuff to their respective game pages, and Galaxy pulled the data shortly after. Try that.

**Comment by massimilianodelliubaldini** [comment]
Sigh, speak of the devil. Cover art literally just appeared on that page...

**Comment by molitar** [comment]
ok so is there an easy fix to make it pull the cover art for it?

**Comment by massimilianodelliubaldini** [comment]
Not to my knowledge. Can you launch the game from GOG?

**Comment by molitar** [comment]
Yes the game launches fine.

**Comment by massimilianodelliubaldini** [comment]
Then I'm assuming the plug-in is working correctly now, since Galaxy itself handles all the metadata pulled after import. You can submit another issue if another problem arises. Thanks!
