### ISSUE TITLE
Plugin is crashing on GOG v2.0.9.136

### ISSUE THREAD

**Issue by adb0t** [mpm11011/galaxy-integration-rpcs3#18]
The plugin always crash when trying to connect on GOG v2.0.9.136

**Comment by massimilianodelliubaldini** [comment]
Can you attach your log files?

```C:\ProgramData\GOG.com\Galaxy\logs\plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log```
```C:\ProgramData\GOG.com\Galaxy\logs\GalaxyClient.log```

Also please upload the contents of ```config.py```.

**Comment by adb0t** [comment]
Here it is:

[plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3922110/plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log)

[GalaxyClient.log](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3922127/GalaxyClient.log)

[config.py.txt](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3922140/config.py.txt)


Thanks..

**Comment by massimilianodelliubaldini** [comment]
In your config.py, on line 11, you have ```self.main_directory = 'D:\Program Files\RPCS3'```

Replace that with ```self.main_directory = 'D:/Program Files/RPCS3'``` per the instructions on line 10. Try that and let me know if it still crashes. Thanks!

**Comment by massimilianodelliubaldini** [comment]
Also, make sure you pull the latest source code. I noticed you have an older version of config.py that is missing some bugfixes.

**Comment by adb0t** [comment]
It still crashes.. BTW it is in GOG version 2.0.11.2 if that helps?

[plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3935967/plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log)

[GalaxyClient.log](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3935968/GalaxyClient.log)

[config.py.txt](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3935969/config.py.txt)

Also, I've redownloaded the plugin on this link https://github.com/mpm11011/galaxy-integration-rpcs3

**Comment by adb0t** [comment]
Okay I re-downloaded it (AGAIN) then downloaded the devita files and configured the self.main_directory (AGAIN) and it WORKED... 

I do not know how the plugin read my game in RPCS3 and sync it to GOG 2 since my games.yml has nothing.
